Algoritmo "SOMA_DOIS_NÚMEROS"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
  valor1, valor2, soma: real


Inicio
      escreval("Digite um valor: ")
      leia(valor1)
      escreval("Digite outro valor: ")
      leia(valor2)
      
      soma <- valor1 + valor2
      
      escreva("A soma desses dois números é: ", soma)
      


Fimalgoritmo